## Name=Priti Subhash Nhavi
## ML 05

# Q1: Take 5 students and their marks 3 subject and calculate the total & average of each student.

In [1]:
def school(n):
    name=[]
    for x in range(n):
        nm=input("Enter the name: ")
        name.append(nm)
    return name
def marks():
    details=[]
    marks=[]
    name=school(5)
    print("marks function: ")
    for x in name:
        print("my name is ",x)
        details.append(x)
        details.append("My marks")
        for x1 in range(3):
            m=int(input("Enter the marks: "))
            marks.append(m)
            details.append(m)
        details.append("Total MArks: ")
        total=sum(marks)
        details.append(total)
        details.append("Average: ")
        avg=total/len(marks)
        details.append(avg)
        print("My marks are: ", details)
        marks.clear()
marks()

Enter the name: priti
Enter the name: kirti
Enter the name: arati
Enter the name: sagar
Enter the name: yash
marks function: 
my name is  priti
Enter the marks: 99
Enter the marks: 98
Enter the marks: 90
My marks are:  ['priti', 'My marks', 99, 98, 90, 'Total MArks: ', 287, 'Average: ', 95.66666666666667]
my name is  kirti
Enter the marks: 91
Enter the marks: 92
Enter the marks: 93
My marks are:  ['priti', 'My marks', 99, 98, 90, 'Total MArks: ', 287, 'Average: ', 95.66666666666667, 'kirti', 'My marks', 91, 92, 93, 'Total MArks: ', 276, 'Average: ', 92.0]
my name is  arati
Enter the marks: 93
Enter the marks: 94
Enter the marks: 95
My marks are:  ['priti', 'My marks', 99, 98, 90, 'Total MArks: ', 287, 'Average: ', 95.66666666666667, 'kirti', 'My marks', 91, 92, 93, 'Total MArks: ', 276, 'Average: ', 92.0, 'arati', 'My marks', 93, 94, 95, 'Total MArks: ', 282, 'Average: ', 94.0]
my name is  sagar
Enter the marks: 96
Enter the marks: 97
Enter the marks: 98
My marks are:  ['priti', 'My ma

# Q2 take10 names in list and shoq the 

### 1)-4 indx person in a variable

In [2]:
list=["priti","simran","kshama","sujata","santosh","amog","shri","kiran","shital","nikita"]
print(list[-4])

shri


# show[-2:3]

In [3]:
print(list[-2:3])

[]


# show [3:-1]

In [4]:
print(list[3:-1])

['sujata', 'santosh', 'amog', 'shri', 'kiran', 'shital']


# add sachin in -3 position

In [5]:
list.insert(-3,"Sachin")

In [6]:
list

['priti',
 'simran',
 'kshama',
 'sujata',
 'santosh',
 'amog',
 'shri',
 'Sachin',
 'kiran',
 'shital',
 'nikita']

# add rahul in last position

In [7]:
list.append("Rahul")

In [8]:
list

['priti',
 'simran',
 'kshama',
 'sujata',
 'santosh',
 'amog',
 'shri',
 'Sachin',
 'kiran',
 'shital',
 'nikita',
 'Rahul']

# use pop function

In [9]:
list.pop()

'Rahul'

In [10]:
list

['priti',
 'simran',
 'kshama',
 'sujata',
 'santosh',
 'amog',
 'shri',
 'Sachin',
 'kiran',
 'shital',
 'nikita']

# how to check the length & print the "Data Science", string the length of list

In [11]:
a=len(list)

In [12]:
for x in range(a):
    print("Data Science")

Data Science
Data Science
Data Science
Data Science
Data Science
Data Science
Data Science
Data Science
Data Science
Data Science
Data Science


# how to clear & delet the list

In [13]:
list.clear()

In [14]:
list

[]

In [15]:
del list

In [16]:
print(list)

<class 'list'>


# Q3 perform arithmatic operation using function

In [17]:
def priti():
    a=2
    b=3
    print(a+b)
    print(a-b)
    print(a*b)
    print(a/b)

In [18]:
priti()

5
-1
6
0.6666666666666666


# Q4 Data analysis on "Medical Insurance"

In [19]:
import pandas as pd
import numpy as np

In [20]:
data=pd.read_csv(r"C:\Users\Lenovo\Downloads\insurance.csv")
data

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

# What are the average charges of southeast & northeast female medical insurance

In [21]:
data.pivot_table(index=["sex","region"],aggfunc="mean")

age        bmi  children      expenses
sex    region                                                 
female northeast  39.639752  29.331056  1.006211  12953.203106
       northwest  39.591463  29.277439  1.115854  12479.870244
       southeast  39.108571  32.673143  1.051429  13499.669257
       southwest  39.703704  30.060494  1.123457  11274.411667
male   northeast  38.901840  29.023313  1.085890  13854.005767
       northwest  38.795031  29.124845  1.180124  12354.119317
       southeast  38.783069  33.994709  1.047619  15879.617354
       southwest  39.208589  31.129448  1.159509  13412.884233

# Q2 Make a category of age like kid,teenage, adult age, oldage

In [22]:
data1=[]
for x in data['age']:
    if x>=0 and x<15:
        data1.append("kid")
    elif x>=15 and x<30:
        data1.append("teenage")
    elif x>=30 and x<50:
        data1.append("adult")
    else:
        data1.append("Oldage")
data["Age_cat"]=data1

In [23]:
data

age     sex   bmi  children smoker     region  expenses  Age_cat
0      19  female  27.9         0    yes  southwest  16884.92  teenage
1      18    male  33.8         1     no  southeast   1725.55  teenage
2      28    male  33.0         3     no  southeast   4449.46  teenage
3      33    male  22.7         0     no  northwest  21984.47    adult
4      32    male  28.9         0     no  northwest   3866.86    adult
...   ...     ...   ...       ...    ...        ...       ...      ...
1333   50    male  31.0         3     no  northwest  10600.55   Oldage
1334   18  female  31.9         0     no  northeast   2205.98  teenage
1335   18  female  36.9         0     no  southeast   1629.83  teenage
1336   21  female  25.8         0     no  southwest   2007.95  teenage
1337   61  female  29.1         0    yes  northwest  29141.36   Oldage

[1338 rows x 8 columns]

# Q3 Show female and male medical average cost by category

In [24]:
data.pivot_table(index=["sex","Age_cat"],aggfunc="mean")

age        bmi  children      expenses
sex    Age_cat                                              
female Oldage   56.635897  31.239487  1.020513  17144.973641
       adult    39.770677  30.347368  1.360902  12244.954962
       teenage  22.527363  29.588557  0.746269   8560.364925
male   Oldage   56.568421  32.098421  0.810526  18680.067105
       adult    39.640741  30.815556  1.551852  13989.212407
       teenage  22.486111  30.093056  0.837963   9761.406759

# Q4 Show the female and male count by category

In [25]:
data.pivot_table(index=["sex","Age_cat"],aggfunc="count")

age  bmi  children  expenses  region  smoker
sex    Age_cat                                              
female Oldage   195  195       195       195     195     195
       adult    266  266       266       266     266     266
       teenage  201  201       201       201     201     201
male   Oldage   190  190       190       190     190     190
       adult    270  270       270       270     270     270
       teenage  216  216       216       216     216     216

# Q5 Show the adult & oldage BMI of smokers

In [26]:
data3=data.iloc[:,[2,4,7]]
data3

bmi smoker  Age_cat
0     27.9    yes  teenage
1     33.8     no  teenage
2     33.0     no  teenage
3     22.7     no    adult
4     28.9     no    adult
...    ...    ...      ...
1333  31.0     no   Oldage
1334  31.9     no  teenage
1335  36.9     no  teenage
1336  25.8     no  teenage
1337  29.1    yes   Oldage

[1338 rows x 3 columns]

In [27]:
data4=data3.loc[((data["Age_cat"]=="adult")|(data["Age_cat"]=="Oldage"))&(data["smoker"]=="yes")]
data4

bmi smoker Age_cat
11    26.3    yes  Oldage
19    35.3    yes   adult
23    31.9    yes   adult
29    36.3    yes   adult
38    36.7    yes   adult
...    ...    ...     ...
1307  28.1    yes   adult
1314  23.7    yes   adult
1321  26.7    yes  Oldage
1323  40.4    yes   adult
1337  29.1    yes  Oldage

[188 rows x 3 columns]

## Q6 Show the peoples less than 10000 charges those are doing smoker daily

In [28]:
data5=data.loc[(data["expenses"]<1000)&(data["smoker"]=="yes")]
data5

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, expenses, Age_cat]
Index: []

# Machine Learning - Dry Beans Dataset

Imbalance,  
Stratified Technique,
 KNN,
 Naive Bayes

In [29]:
data=pd.read_csv(r"C:\Users\Lenovo\Desktop\Python\Datasets\Dry_Bean.csv")

In [30]:
data

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653247  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

          Class  
0         SEKER  
1         SEKER  
2         SEKER  
3         SEKER  
4         SEKER  
...         ...  
13606  DERMASON  
13607  DERMASON  
13608  DERMASON  
13609  DERMASON  
13610  DERMASON  

[13611 rows x 17 columns]

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13611 entries, 0 to 13610
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             13611 non-null  int64  
 1   Perimeter        13611 non-null  float64
 2   MajorAxisLength  13611 non-null  float64
 3   MinorAxisLength  13611 non-null  float64
 4   AspectRation     13611 non-null  float64
 5   Eccentricity     13611 non-null  float64
 6   ConvexArea       13611 non-null  int64  
 7   EquivDiameter    13611 non-null  float64
 8   Extent           13611 non-null  float64
 9   Solidity         13611 non-null  float64
 10  roundness        13611 non-null  float64
 11  Compactness      13611 non-null  float64
 12  ShapeFactor1     13611 non-null  float64
 13  ShapeFactor2     13611 non-null  float64
 14  ShapeFactor3     13611 non-null  float64
 15  ShapeFactor4     13611 non-null  float64
 16  Class            13611 non-null  object 
dtypes: float64(1

In [32]:
data.describe()

Area     Perimeter  MajorAxisLength  MinorAxisLength  \
count   13611.000000  13611.000000     13611.000000     13611.000000   
mean    53048.284549    855.283459       320.141867       202.270714   
std     29324.095717    214.289696        85.694186        44.970091   
min     20420.000000    524.736000       183.601165       122.512653   
25%     36328.000000    703.523500       253.303633       175.848170   
50%     44652.000000    794.941000       296.883367       192.431733   
75%     61332.000000    977.213000       376.495012       217.031741   
max    254616.000000   1985.370000       738.860154       460.198497   

       AspectRation  Eccentricity     ConvexArea  EquivDiameter        Extent  \
count  13611.000000  13611.000000   13611.000000   13611.000000  13611.000000   
mean       1.583242      0.750895   53768.200206     253.064220      0.749733   
std        0.246678      0.092002   29774.915817      59.177120      0.049086   
min        1.024868      0.218951   20684.000000     161.243764      0.555315   
25%        1.432307      0.715928   36714.500000     215.068003      0.718634   
50%        1.551124      0.764441   45178.000000     238.438026      0.759859   
75%        1.707109      0.810466   62294.000000     279.446467      0.786851   
max        2.430306      0.911423  263261.000000     569.374358      0.866195   

           Solidity     roundness   Compactness  ShapeFactor1  ShapeFactor2  \
count  13611.000000  13611.000000  13611.000000  13611.000000  13611.000000   
mean       0.987143      0.873282      0.799864      0.006564      0.001716   
std        0.004660      0.059520      0.061713      0.001128      0.000596   
min        0.919246      0.489618      0.640577      0.002778      0.000564   
25%        0.985670      0.832096      0.762469      0.005900      0.001154   
50%        0.988283      0.883157      0.801277      0.006645      0.001694   
75%        0.990013      0.916869      0.834270      0.007271      0.002170   
max        0.994677      0.990685      0.987303      0.010451      0.003665   

       ShapeFactor3  ShapeFactor4  
count  13611.000000  13611.000000  
mean       0.643590      0.995063  
std        0.098996      0.004366  
min        0.410339      0.947687  
25%        0.581359      0.993703  
50%        0.642044      0.996386  
75%        0.696006      0.997883  
max        0.974767      0.999733

In [33]:
data.isnull().sum()

Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64

## Label Encoding

In [34]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data["Class"]=l.fit_transform(data["Class"])

In [35]:
data

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653247  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

       Class  
0          5  
1          5  
2          5  
3          5  
4          5  
...      ...  
13606      3  
13607      3  
13608      3  
13609      3  
13610      3  

[13611 rows x 17 columns]

In [36]:
data["Class"].value_counts()

3    3546
6    2636
5    2027
4    1928
2    1630
0    1322
1     522
Name: Class, dtype: int64

In [37]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

## Imbalancing 

In [38]:
from imblearn.over_sampling import RandomOverSampler
r=RandomOverSampler()
x_data,y_data=r.fit_resample(x,y)

In [39]:
from collections import Counter
print(Counter(y_data))

Counter({5: 3546, 0: 3546, 1: 3546, 2: 3546, 4: 3546, 6: 3546, 3: 3546})


In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.3,random_state=51)

In [41]:
print(Counter(y_train))

Counter({5: 2507, 4: 2494, 0: 2491, 2: 2481, 3: 2479, 6: 2474, 1: 2449})


In [42]:
print(len(x_train))

17375


In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [47]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [48]:
pred=knn.predict(x_test)
pred

array([4, 5, 0, ..., 5, 6, 2])

# Naive Bayes

In [49]:
from sklearn.naive_bayes import GaussianNB

In [51]:
from sklearn.metrics import accuracy_score
nb=GaussianNB()
nb.fit(x_train,y_train)
nb_pred=nb.predict(x_test)
nb_acc=accuracy_score(nb_pred,y_test)*100
print("Accuracy score of naive bayes: ",nb_acc)

Accuracy score of naive bayes:  77.31972606418692


In [52]:
print((x_train).shape)
print((x_test).shape)
print((y_train).shape)
print((y_test).shape)

(17375, 16)
(7447, 16)
(17375,)
(7447,)


In [53]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold()
skf.get_n_splits(x_data,y_data)

5

In [54]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [55]:
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    
    scores=cross_val_score(nb,x_train,y_train,cv=skf)
    y_pred=cross_val_predict(nb,x_test,y_test)
    
    print("Checking the balance: ",Counter(y_test))
    print(scores)
    print(y_pred)
    print(np.mean(scores)*100)

Checking the balance:  Counter({5: 710, 6: 710, 0: 709, 1: 709, 2: 709, 4: 709, 3: 709})
[0.87713998 0.88997986 0.75900277 0.7250063  0.62477965]
[3 3 3 ... 1 1 1]
77.5181711415821
Checking the balance:  Counter({0: 710, 3: 710, 5: 709, 2: 709, 4: 709, 6: 709, 1: 709})
[0.46827795 0.83559919 0.7612692  0.7192143  0.64265928]
[5 5 5 ... 1 1 1]
68.54039850345012
Checking the balance:  Counter({1: 710, 5: 709, 2: 709, 4: 709, 6: 709, 3: 709, 0: 709})
[0.57703927 0.887714   0.84239678 0.67212289 0.6408965 ]
[5 5 5 ... 5 5 5]
72.4033888186837
Checking the balance:  Counter({2: 710, 6: 709, 3: 709, 0: 709, 1: 709, 4: 709, 5: 709})
[0.51636455 0.91414904 0.88318228 0.69025434 0.65802065]
[6 6 6 ... 6 5 5]
73.23941729604083
Checking the balance:  Counter({4: 710, 3: 709, 0: 709, 1: 709, 2: 709, 5: 709, 6: 709})
[0.52089627 0.90231621 0.89602216 0.7250063  0.62553513]
[3 5 5 ... 6 6 6]
73.39552135662302


# Water Potability

In [56]:
data=pd.read_csv(r"C:\Users\Lenovo\Desktop\Python\Datasets\water_potability.csv")
data

ph    Hardness        Solids  Chloramines     Sulfate  \
0          NaN  204.890455  20791.318981     7.300212  368.516441   
1     3.716080  129.422921  18630.057858     6.635246         NaN   
2     8.099124  224.236259  19909.541732     9.275884         NaN   
3     8.316766  214.373394  22018.417441     8.059332  356.886136   
4     9.092223  181.101509  17978.986339     6.546600  310.135738   
...        ...         ...           ...          ...         ...   
3271  4.668102  193.681735  47580.991603     7.166639  359.948574   
3272  7.808856  193.553212  17329.802160     8.061362         NaN   
3273  9.419510  175.762646  33155.578218     7.350233         NaN   
3274  5.126763  230.603758  11983.869376     6.303357         NaN   
3275  7.874671  195.102299  17404.177061     7.509306         NaN   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       564.308654       10.379783        86.990970   2.963135           0  
1       592.885359       15.180013        56.329076   4.500656           0  
2       418.606213       16.868637        66.420093   3.055934           0  
3       363.266516       18.436524       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
...            ...             ...              ...        ...         ...  
3271    526.424171       13.894419        66.687695   4.435821           1  
3272    392.449580       19.903225              NaN   2.798243           1  
3273    432.044783       11.039070        69.845400   3.298875           1  
3274    402.883113       11.168946        77.488213   4.708658           1  
3275    327.459760       16.140368        78.698446   2.309149           1  

[3276 rows x 10 columns]

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB


In [58]:
data.describe()

ph     Hardness        Solids  Chloramines      Sulfate  \
count  2785.000000  3276.000000   3276.000000  3276.000000  2495.000000   
mean      7.080795   196.369496  22014.092526     7.122277   333.775777   
std       1.594320    32.879761   8768.570828     1.583085    41.416840   
min       0.000000    47.432000    320.942611     0.352000   129.000000   
25%       6.093092   176.850538  15666.690297     6.127421   307.699498   
50%       7.036752   196.967627  20927.833607     7.130299   333.073546   
75%       8.062066   216.667456  27332.762127     8.114887   359.950170   
max      14.000000   323.124000  61227.196008    13.127000   481.030642   

       Conductivity  Organic_carbon  Trihalomethanes    Turbidity   Potability  
count   3276.000000     3276.000000      3114.000000  3276.000000  3276.000000  
mean     426.205111       14.284970        66.396293     3.966786     0.390110  
std       80.824064        3.308162        16.175008     0.780382     0.487849  
min      181.483754        2.200000         0.738000     1.450000     0.000000  
25%      365.734414       12.065801        55.844536     3.439711     0.000000  
50%      421.884968       14.218338        66.622485     3.955028     0.000000  
75%      481.792304       16.557652        77.337473     4.500320     1.000000  
max      753.342620       28.300000       124.000000     6.739000     1.000000

# Data preprocessing

In [59]:
data.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [60]:
a=data['Sulfate'].mean()
b=data['ph'].mean()
c=data['Trihalomethanes'].mean()

In [61]:
data['Sulfate'].fillna(a,inplace=True)
data['ph'].fillna(b,inplace=True)
data['Trihalomethanes'].fillna(c,inplace=True)

In [62]:
data

ph    Hardness        Solids  Chloramines     Sulfate  \
0     7.080795  204.890455  20791.318981     7.300212  368.516441   
1     3.716080  129.422921  18630.057858     6.635246  333.775777   
2     8.099124  224.236259  19909.541732     9.275884  333.775777   
3     8.316766  214.373394  22018.417441     8.059332  356.886136   
4     9.092223  181.101509  17978.986339     6.546600  310.135738   
...        ...         ...           ...          ...         ...   
3271  4.668102  193.681735  47580.991603     7.166639  359.948574   
3272  7.808856  193.553212  17329.802160     8.061362  333.775777   
3273  9.419510  175.762646  33155.578218     7.350233  333.775777   
3274  5.126763  230.603758  11983.869376     6.303357  333.775777   
3275  7.874671  195.102299  17404.177061     7.509306  333.775777   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       564.308654       10.379783        86.990970   2.963135           0  
1       592.885359       15.180013        56.329076   4.500656           0  
2       418.606213       16.868637        66.420093   3.055934           0  
3       363.266516       18.436524       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
...            ...             ...              ...        ...         ...  
3271    526.424171       13.894419        66.687695   4.435821           1  
3272    392.449580       19.903225        66.396293   2.798243           1  
3273    432.044783       11.039070        69.845400   3.298875           1  
3274    402.883113       11.168946        77.488213   4.708658           1  
3275    327.459760       16.140368        78.698446   2.309149           1  

[3276 rows x 10 columns]

In [63]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [64]:
from collections import Counter
print(Counter(y))

Counter({0: 1998, 1: 1278})


In [65]:
from imblearn.over_sampling import RandomOverSampler

In [66]:
s=RandomOverSampler()
x_data,y_data=s.fit_resample(x,y)

In [67]:
print(Counter(y_data))

Counter({0: 1998, 1: 1998})


In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.3,random_state=99)

In [69]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
x_data1=s.fit_transform(x_data)
x_data1

array([[ 8.87894883e-04,  2.67026194e-01, -1.46061819e-01, ...,
        -1.17603087e+00,  1.29950415e+00, -1.29955134e+00],
       [-2.31893266e+00, -2.00768334e+00, -3.90871244e-01, ...,
         2.77623078e-01, -6.31796098e-01,  6.86810805e-01],
       [ 7.02980802e-01,  8.50138980e-01, -2.45942106e-01, ...,
         7.88989126e-01,  3.80658333e-03, -1.17966278e+00],
       ...,
       [ 2.16064668e-02,  5.38176129e-01,  3.35593085e-01, ...,
         6.41966208e-01,  1.59491661e+00,  2.25279978e+00],
       [ 8.06693041e-01,  1.05198416e+00,  1.22536574e+00, ...,
         8.44270088e-01,  2.15540396e-01,  4.07980826e-01],
       [ 7.60191203e-01, -2.82151882e-01, -2.76202299e-01, ...,
        -8.30255384e-01, -6.84402492e-01,  8.21922275e-01]])

In [70]:
y_data1=y_data

In [71]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x_data1,y_data1,test_size=0.3,random_state=57)

# Logistic Regression

In [72]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(x_train1,y_train1)
log_pred=log.predict(x_test1)
log_acc=accuracy_score(y_test1,log_pred)*100
print("accuracy_score of logstic",log_acc)

accuracy_score of logstic 48.37364470391993


# SVM

In [73]:
from sklearn.svm import SVC
s1=SVC(random_state=187)
s1.fit(x_train1,y_train1)
s1_pred=s1.predict(x_test1)
s1_acc=accuracy_score(s1_pred,y_test1)*100
print("accuracy_score of SVM",s1_acc)

accuracy_score of SVM 65.05421184320267
